### ISSUE TITLE
Неверный URL формы

### ISSUE THREAD

**Issue by sashabeep** [mnoskov/commerce-payment-robokassa#2]
В скрипте написан 
http://merchant.roboxchange.com

А должно быть 
https://auth.robokassa.ru/Merchant/Index.aspx

![Снимок экрана 2020-04-12 в 17 12 55](https://user-images.githubusercontent.com/5689796/79070838-dec21000-7ce0-11ea-89fe-3fa2d20c2642.png)

**Comment by sashabeep** [comment]
https://github.com/mnoskov/commerce-payment-robokassa/pull/3

**Comment by mnoskov** [comment]
Кто же их, эти доки, читает то.

**Comment by sashabeep** [comment]
@mnoskov просто раньше редирект работал, видимо, а сейчас отваливаться стал
